project:
  type: website
  output-dir: docs

website:
  title: "Data Brain Storm"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/JayLBean/
      - icon: twitter
        href: https://twitter.com
  page-footer: 
    center: "Â© 2026 Yusheng Li. Powered by Quarto."

format:
  html:
    theme: 
      light: litera
    css: styles.css 
    toc: true 
    toc-title: "On this page"
    code-copy: true 
    highlight-style: github 



